services:
  - type: web
    plan: free
    name: MD_File_bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/moviesdude/MD-file-bot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_OWNER
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: LAZY_PIC
        sync: false
      - key: LOG_CHANNEL
        sync: false    
      - key: BOT_USERNAME
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: DB_CHANNEL
        sync: false
      - key: LAZY_MODE
        sync: false
      - key: FORWARD_AS_COPY
        sync: false
      - key: BROADCAST_AS_COPY
        sync: false
      - key: BANNED_USERS
        sync: false
      - key: BANNED_CHAT_IDS
        sync: false
      - key: OTHER_USERS_CAN_SAVE_FILE
        sync: false
      - key: LAZY_CHANNEL
        sync: false
    autoDeploy: false
